// Copyright (C) 2025 Laurynas 'Deviltry' Ekekeke
// SPDX-License-Identifier: BSD-3-Clause

#ifndef WSLEDS_DATA_H
#define WSLEDS_DATA_H

// COLORS

#define COLOR_YELLOW	0b11111111'11111111'00000000
#define COLOR_ORANGE 	0b11111111'00011011'00000000
#define COLOR_GREEN  	0b00000000'11111111'00000000
#define COLOR_RED    	0b11111111'00000000'00000000
#define COLOR_WHITE  	0b11111111'11111111'11111111
#define COLOR_BLUE   	0b00000000'00000000'11111111
#define COLOR_PURPLE 	0b11111111'00000000'11111111
#define COLOR_CYAN   	0b00000000'11111111'11111111
#define COLOR_OFF    	0b00000000'00000000'00000000

static const u32 WSLEDS_NUMBERS[10][64] = {
	// 0:
	{
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF
	},
	// 1:
	{
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF
	},
	// 2:
	{
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF
	},
	// 3:
	{
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF
	},
	// 4:
	{
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF
	},
	// 5:
	{
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF
	},
	// 6:
	{
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF
	},
	// 7:
	{
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF
	},
	// 8:
	{
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF
	},
	// 9:
	{
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_WHITE, COLOR_WHITE, COLOR_OFF, COLOR_OFF, COLOR_OFF,
		COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF, COLOR_OFF
	}
};

#endif //WSLEDS_DATA_H
